FROM ubuntu:18.04
WORKDIR /azp
# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
# Set default locale for the environment
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
RUN apt-get update \
&& apt-get install -y locales \
&& dpkg-reconfigure locales \
&& locale-gen en_US.UTF-8 \
&& /usr/sbin/update-locale LANG=C.UTF-8

# Install needed default locale for Makefly
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && \
  locale-gen

RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
&& curl -sL https://aka.ms/InstallAzureCLIDeb | bash

COPY ./Jekyll .

RUN apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libicu60 \
        libunwind8 \
        netcat \
        wget \
        software-properties-common \
        ruby-full \
        build-essential \
        zlib1g-dev \
&& gem install jekyll \
&& gem install bundler -v 1.17.2 \
&& bundle install 
#&& wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
#&& dpkg -i packages-microsoft-prod.deb \
#&& add-apt-repository universe \
#&& apt-get update \
#&& apt-get install -y --no-install-recommends powershell
COPY ./start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]